import React from 'react'
import style from "./cartpage.module.scss"
import CartPageContainer from './CartPageContainer';
import TopCartPage from './TopCartPage';
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Cart',
  description: 'Generated by create next app',
}


export default function page() {

  return (
    <div className={style.cartPage}>
      <div className={style.innerCartPage}>
        <h1 className={style.cartTitle}>Cart</h1>
        <TopCartPage />
        <CartPageContainer />
      </div>
    </div>
  )
}
