import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import { CartProvider } from '@/context/CartItems'
import Footer from '@/components/Footer/Footer'
import { StyleProvider } from '@/context/StyleContext'
import { SortProvider } from '@/context/SortContext'
import ResponsiveFooter from '@/components/ResponsiveFooter'
import ResponsiveSort from '@/components/ResponsiveSort'

const raleway = Raleway({ 
  weight: ['400','600', '800'],
  subsets: ['latin']
 })

export const metadata: Metadata = {
  title: 'GiorgiMachitadze | Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <CartProvider>
          <SortProvider>
            <ResponsiveSort />
            <StyleProvider>
              <Navbar />
              <ResponsiveFooter />
            </StyleProvider>
            {children}
            <Footer />
          </SortProvider>
        </CartProvider>
      </body>
    </html>
  )
}