import React from 'react'
import style from "./jewelry.module.scss"
import JewelryContainer from './jewelryContainer'
import type { Metadata } from 'next'
import JewelryHeader from './JewelryHeader/JewelryHeader'


export const metadata: Metadata = {
  title: 'Jewelry',
  description: 'Generated by create next app',
}

export default function jewelry() {
  

  return (
    <main className={style.jewelry}>
      <JewelryHeader />
      <div className={style.innerMain}>
        <div className={style.categoryName}>
          <h1>Jewelry</h1>
        </div>
        <div className={style.cardContainer}>
          <JewelryContainer />
        </div>
      </div>
    </main>
  )
}
