import React from 'react'
import style from "./jewelry.module.scss"
import type { Metadata } from 'next'
import JewelryHeader from './_components/JewelryHeader/JewelryHeader'
import { fetchByCategory } from "@/utils/fetchByCategory";
import JewelryContent from './_components/JewelryContent/JewelryContent';

export const metadata: Metadata = {
  title: 'Jewelry',
  description: 'Generated by create next app',
}

export default async function jewelry() {
  const data = await fetchByCategory(`jewelery`);

  return (
    <main className={style.jewelry}>
      <JewelryHeader />
      <JewelryContent data={data} />
    </main>
  )
}
