import React from 'react'
import style from "./clothing.module.scss"
import type { Metadata } from 'next'
import { fetchByCategory } from '@/utils/fetchByCategory'
import ClothingHeader from './_components/ClothingHeader/ClothingHeader'
import ClothingContent from './_components/ClothingContent/ClothingContent'

export const metadata: Metadata = {
  title: 'Clothing',
  description: 'Generated by create next app',
}


export default async function jewelry() {
  const womenData = await fetchByCategory(`women's clothing`);
  const menData = await fetchByCategory(`men's clothing`);

  return (
    <main className={style.clothing}>
      <ClothingHeader />
      <ClothingContent womenData={womenData} menData={menData} />
    </main>
  )
}