import React from 'react'
import style from "./clothing.module.scss"
import MenContainer from './menContainer'
import WomenContainer from './womenContainer'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Clothing',
  description: 'Generated by create next app',
}


export default function jewelry() {
  

  return (
    <main className={style.clothing}>
      <div className={style.innerMain}>
        <div className={style.categoryName}>
          <h1>Men&apos;s Clothing</h1>
        </div>
        <div className={style.cardContainer}>
          <MenContainer />
        </div>
        <div className={style.categoryName}>
          <h1>Women&apos;s Clothing</h1>
        </div>
        <div className={style.cardContainer}>
          <WomenContainer />
        </div>
      </div>
    </main>
  )
}